name: Unit tests

on: [push, pull_request]

env:
  CODECOV_PY_VER: '3.10'

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', 3.11]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Set up python-${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run unit tests
        run: |
          BEKA_TESTS=-uz ./run_tests.sh
      - if: ${{ matrix.python-version == env.CODECOV_PY_VER }}
        name: Upload codecov
        uses: codecov/codecov-action@v5
